name: generate-jekyll-pages-for-docs

on:
  workflow_run:
    workflows:
      - generate-latest-docs-on-ghp
      - generate-manually-docs-on-ghp
      - generate-release-docs-on-ghp
    branches:
      - main
    types:
      - completed

jobs:
  generate-jekyll-pages:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Generate pages from present docs folders and templates
        run: bash .generate-pages/generate-pages.sh
        env:
          MASTER_BRANCH_NAME: main
          SOURCE_INDEX_FILE: README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v8.0.1



