name: generate-jekyll-pages-for-docs

on:
  workflow_run:
    workflows: 
      - generate-latest-docs-on-ghp
      - generate-release-docs-on-ghp
      - generate-manually-docs-on-ghp
    branches: 
      - main
    types: 
      - completed

jobs:
  generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with: 
          ref: gh-pages

      - name: Generate pages from present docs folders and templates
        run: bash .github/generate-pages/generate-pages.sh
        env:
          TARGET_VERSIONS_FILE: _data/versions.csv
          TARGET_VERSION_PAGES_LOCATION: pages/versions
          SOURCE_INDEX_FILE: README.md
          SOURCE_TEMPLATES_LOCATION: .github/workflows/generate-pages/templates

      - name: Commit changes
        uses: EndBug/add-and-commit@v8.0.1



