# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build

  publish-docs-reports:
    needs: build	
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Export project version
        run: echo "PROJECT_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')" >> $GITHUB_ENV
      
      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Run tests and generate reports
        run: ./gradlew test

      - name: Deploy tests results to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/tests
          target-folder: docs/latest/junit
      - name: Deploy jacoco report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/jacoco
          target-folder: docs/latest/jacoco
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: docs/latest/javadoc

      - name: Deploy tests results to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/tests
          target-folder: docs/${{ env.PROJECT_VERSION }}/junit
      - name: Deploy jacoco report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/reports/jacoco
          target-folder: docs/${{ env.PROJECT_VERSION }}/jacoco
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          clean: true
          folder: build/docs/javadoc
          target-folder: docs/${{ env.PROJECT_VERSION }}/javadoc